### PR TITLE
add isOpen prop

### PR DESCRIPTION
**Pull request by nd0ut**

### CODE REVIEW

**Comment by moroshko** [comment]
@nd0ut Could you explain please what issue are you trying to address with this PR?

**Comment by nd0ut** [comment]
@moroshko Yeah, I'm sorry. I'm building a custom suggestion input control for my app based on react-autowhatever and I just wanted to control if the suggestion list opened or not. I don't want the list to be opened all the time if there is any items passed in it.

**Comment by moroshko** [comment]
@nd0ut I see your point, but I'm not sure that `isOpen` deserves it's own prop in this project.
The idea of `react-autowhatever` is to provide a view layer without any logic. If you want suggestions to be rendered, pass them. If you don't, don't pass them. It's that simple. So, instead of doing:

    <Autowhatever isOpen={false} suggestions={['item1', 'item2']} ... />

just do:

    <Autowhatever suggestions={[]} ... />

**Comment by nd0ut** [comment]
Oh, I remembered why I actually did that patch with `isOpen` instead of passing empty items. I wanted to make `leave` animation of the item list but it's impossible cause the list is removing from DOM instantly.

You're right about `isOpen`. I think better solution is to allow the user to manually wrap an `ul` element with `ReactCSSTransitionGroup` for example. What do you think?

**Comment by moroshko** [comment]
@nd0ut Sorry it took me so long to get back to you.

I think adding a hook to wrap the `ul` makes sense.

**Comment by moroshko** [comment]
@nd0ut Would you be interested to contribute, or did you find a workaround and we can close this issue for now?

**Comment by moroshko** [comment]
@nd0ut I added a new `renderItemsContainer` prop to provide a way to limit the scrolling to the items container only. I suspect it might help you with the animation implementation.

**Pull request closed without merging**
