### PR TITLE
Fix theming for aphrodite

### PR DESCRIPTION
**Pull request by ferdinandsalis**
Now allows either an object or an array to be passed to the
theme prop. See this https://github.com/markdalgleish/react-themeable#aphrodite
and https://github.com/markdalgleish/react-themeable/blob/master/src/index.js#L6
for more information.

### CODE REVIEW

**Comment by moroshko** [comment]
Thanks a lot!

**Comment by ferdinandsalis** [comment]
Your welcome.

Please note I just noticed that Aphrodite does not support descendant selectors so one wont be able to actually use it with `react-autosuggest`. Since it wont be able to do `.containerOpen .suggestionContainer`. Thats a pity, or am I mistaken?

**Comment by moroshko** [comment]
Yeah, you're sadly right. [Here](http://codepen.io/moroshko/pen/zKxypa) is an attempt to translate global CSS to Aphrodite, but because descendant selectors are not yet supported by Aphrodite, we're somewhat stuck.

I guess we could think of a way not to rely on descendant selectors in `react-autowhatever` (and `react-autosuggest`). Let me know if you have ideas.

**Comment by ferdinandsalis** [comment]
I will try to think of something 😊

**Pull request merged**
