### PR TITLE
Ability to render an input with a different element

### PR DESCRIPTION
**Pull request by sapegin**
I want to use it with a masked input component.

### CODE REVIEW

**Comment by sapegin** [comment]
Hey @moroshko, what can I do to make it merged?

**Comment by moroshko** [comment]
Hey @sapegin, sorry it took me so long to get back to you.

Could you explain your use case? What do you mean by a _masked input component_?

`react-autowhatever` provides accessibility out of the box, and I'm concerned about breaking this if I don't know the element I'm rendering.

**Comment by sapegin** [comment]
I want to use another component instead of naive `input`, like [react-input-mask](https://github.com/sanniassin/react-input-mask). It could also make integration with something like React Bootstrap easier.

>  if I don't know the element I'm rendering.

You know it until the user wants to change it ;-)

**Comment by sapegin** [comment]
@moroshko ping.

**Comment by moroshko** [comment]
@sapegin Sorry it took me so long to respond.

I feel like what you suggest is beyond what this project is about. I'll pass on this one. Sorry.

**Comment by sapegin** [comment]
That’s very sad because it was a simple change that won’t affect any current use case but will allow better integration with other libraries.

**Pull request closed without merging**
